name: Automatizar Comentário em Issue

on:
  issues:
    types: [opened]

jobs:
  comentar:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Criar um comentário automático
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Boas-vindas!"
          content-filepath: ".github/ISSUE_TEMPLATE/mensagem.md"
          
