name: Gerenciador de Comandos da Issue

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  comentar_e_fechar:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Comentar na issue automaticamente
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body-path: ".github/ISSUE_TEMPLATE/mensagem.md"

      - name: Fechar a issue se solicitado
        if: github.event_name == 'issue_comment' && github.event.comment.body == 'close issue'
        uses: peter-evans/close-issue@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          
