name: Build BlueEngine

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # INSTALA O NASM NO RUNNER DO GITHUB
    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build build --config Release
      
